#!/usr/bin/env python3
# encoding: utf-8
# -*- coding: utf-8-unix -*-
# vim:fileencoding=utf-8:ff=unix
"""Command line tool to print arguments.
"""

import sys

for arg in sys.argv[1:]:
    print(arg)
